### PR TITLE
Addition of Uart generic profile  

### PR DESCRIPTION
**Pull request by vijay-hcl-epl**
## PR Changes
This PR has the below changes
1. Removal of the existing UART profiles
2. Addressing review comments in the PR#3 & PR#4
3. Adding generic UART profile which supports read and write with any serial device

## Test cases Executed

1. UART Read - Send data from the PC
2. UART Write - Write data from the Rasp Pi
3. Auto events
4. device commands
5. Multiple device resources in device commands

Test setup and procedure is mentioned in README file

### CODE REVIEW

**Comment by vijay-hcl-epl** [comment]
Hi @iain-anderson 
Could you please review this and let me know your comments? 

Thanks in advance,
Vijay

**Review by iain-anderson — CHANGES_REQUESTED** [review]
This mostly looks good. A couple of small items:
* Default service port should be 59995
* device-sdk-go should be imported at version 2.2.0
* when extracting a numeric type from an attribute it's easier to use `github.com/spf13/cast` which allows eg `cast.ToUint16E` to get from the `interface` type to the one you want

**Comment by vijay-hcl-epl** [comment]
Thanks Iain for the review. Need some clarifications. Please give your comments
1. Regarding the point 

> "device-sdk-go should be imported at version 2.2.0"

 this change should be in the file go.mod like this "**github.com/edgexfoundry/device-sdk-go/v2 v2.2.0**"? Is that right?

2. Instead of cast.ToUint16E, I am using cast.ToIntE as the base serial go package expects int as the argument for baud. Hope this is fine

Thank You

**Comment by vijay-hcl-epl** [comment]
Hi @iain-anderson Could you please give your clarifications for the above comment? It will be helpful for me to update the code changes and commit.

Thank you.

**Comment by iain-anderson** [comment]
> Thanks Iain for the review. Need some clarifications. Please give your comments
> 
>     1. Regarding the below comment
> 
> > "device-sdk-go should be imported at version 2.2.0"
> 
> this change should be in the file go.mod like this "**github.com/edgexfoundry/device-sdk-go/v2 v2.2.0**"? I should remove "-dev.13" from "v2.2.0-dev.13". Is that right? Please confirm

Yes. Also do the same for go-mod-core-contracts

>     2. Instead of cast.ToUint16E, I am planning to use cast.ToIntE, since the base serial go package expects int as the argument for baud parameter. Hope this is fine

Yes, use whichever cast is suitable

**Comment by vijay-hcl-epl** [comment]
Thank you @iain-anderson for the clarifications. Addressed all the review comments in the commit 2b62209. Please review.

Thank you

**Review by iain-anderson — CHANGES_REQUESTED** [review]
I think you should be able to do `cast.ToIntE(req.Attributes["thing"])` rather than `cast.ToIntE(fmt.Sprintf("%v", req.Attributes["thing"]))`.
Other than that, looks great!

**Comment by vijay-hcl-epl** [comment]
@iain-anderson Made the changes as suggested and added a commit 623d9e1. Please review.

Thank you

**Review by iain-anderson — APPROVED** [review]

**Pull request merged**
